/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.bluefox;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bluefox=0x7f020000;
    }
    public static final class id {
        public static final int ListView=0x7f050016;
        public static final int back=0x7f050006;
        public static final int change_distr_rate=0x7f05000f;
        public static final int change_drupal_url=0x7f050009;
        public static final int change_message_url=0x7f05000c;
        public static final int change_update_rate=0x7f050012;
        public static final int clear_update_log=0x7f050007;
        public static final int configureLog=0x7f050015;
        public static final int days_to_send=0x7f050014;
        public static final int drupalURL_info=0x7f050008;
        public static final int messageURL_info=0x7f05000b;
        public static final int message_distr_rate=0x7f05000e;
        public static final int message_update_rate=0x7f050011;
        public static final int output2=0x7f050004;
        public static final int output3=0x7f050013;
        public static final int refresh=0x7f050005;
        public static final int reset_drupal_url=0x7f05000a;
        public static final int reset_message_url=0x7f05000d;
        public static final int search_akshen=0x7f050000;
        public static final int settings=0x7f050003;
        public static final int show_messages=0x7f050001;
        public static final int stop_distr=0x7f050010;
        public static final int view_update_log=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int settings=0x7f030001;
        public static final int showinfo=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
